:bug: use get_relative_file_path so that report can be generated from subfolder
Now this works and can be run from the docs folder using:
cd docs
vuegen -c example_config_files/Basic_example_vuegen_demo_notebook_config.yaml -output_dir ../tests/report_examples/Basic_example_vuegen_demo_notebook_cfg
streamlit run ../tests/report_examples/Basic_example_vuegen_demo_notebook_cfg/streamlit_report/sections/report_manager.py

diff --git a/.github/workflows/cdci.yml b/.github/workflows/cdci.yml
--- a/.github/workflows/cdci.yml
+++ b/.github/workflows/cdci.yml
@@ -118,6 +118,15 @@ jobs:
             echo "Error: One or more protected files have been modified."
             exit 1
           fi
+      - name: streamlit report based on predefined config file
+        run: |
+          cd docs
+          vuegen -c example_config_files/Basic_example_vuegen_demo_notebook_config.yaml -output_dir ../tests/report_examples/Basic_example_vuegen_demo_notebook_cfg
+          # Check for changes
+          if git diff ../tests/report_examples | grep .; then
+            echo "Error: One or more protected files have been modified."
+            exit 1
+          fi
       - name: check streamlit report files for chatbot API
         run: |
           vuegen -c docs/example_config_files/Chatbot_example_config.yaml -output_dir tests/report_examples/chat_bot
