Style and format codebase (#131)
* :art: format markdowns

* :art: docstrings to 90 characters and remove whitespaces

* :wrench: set line length to 90 characters

* :art: split comments, add comments, remove more whitespace, add more docstrings

* :art: write strings on two line and let Python concatenate theses

* :art: snake_case

* :art: raise ValueError if unknown type is provided

alternatively we could use a meaningful default

* :art: specify encoding explicitly

* :art: use textwrap to keep indentation

* :bug: with textwrap the text cannot contain new line statements

* :art: adjust comments and docstrings to line-length

* :wrench: add jupytext configuration for notebooks to project

* ✅ update example report files so test pass (reviewed changes are only style of .py files)

* :art: continue reformatting of streamlit_report.py

* :art: remove one level of indentation

* :art: docstring and f-string formatting

- leave out most multiline string for now (which need dedenting)
- one whitespace update in tests

* :art: encoding and whitespace updates

* :bug: add missing argument to abc for reports

* :art: textwrap code or html blocks

- sometime indent and dedent has to be used
- one typo (altair plot, not plotly plot corrected)
- new line before python code block in qmd files

* :art: keep urls at the top

- maybe 'Verschlimmbessern': footer can be hard to read (pdf)
- needed to use escaping of {} using unicode:
  \u007b is { and \u007d is }
- :bug: jupyter used relative import -> changed to URL link of LOGO
- unify MONA mentioning (pdf)

* :art: limit remaining lines to 90 characters

* :art: shorten docstrings and comments, implement lazy logging

lazy logging is recommended (only a warning):
https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html

* :art: remove trailing white-space from streamlit footer

* :truck: add constants file to keep these central

* :art: streamlit footer in utils? use central constants for footer, dedent

* :art: add initialization of dictionary in body of function

* :art: add timeout to get request -> will 60 seconds always be enough?

* :art: dedent and slightly modify completion message

* :art: line lenght, lazy logging and raising exceptions from exception

* :art: module and docstrings, comments splitting and removing unnecessary code

* :art: lazy logging + exe_info and Error messaging splitting (line length)

* :art: module string, line length, unused arguments,

* :art: lazy logging and reporting of error info for error

lazy-logging: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-not-lazy.html
exc_info: https://docs.python.org/3/library/logging.html#logging.Logger.debug

* 🐛 Handle error for loading static images from a URL in streamlit reports

* 📝 Update md files for the yaml examples on the documentation

* 🐛 Fix desciption from the EMP config example

* 🐛 Fix code to load images from URLs in streamlit reports

* Trigger GitHub actions to avoid connection error to download tinytex

* :art::wrench: let ruff check for line lenght and other potential bugs, add vscode config

update config:
- fixed line length to 88 as default
- ensure line lenght is checked in tests

* :bug: Ollama chatbot example

- dedent should be called only once
- each block needs to be on the level of where it is supposed to be used (in the multiline f-string)

* :bug: use existing config file, not the local one generated by chabot notebook

---------

Co-authored-by: sayalaruano <sebasar1245@gmail.com>

diff --git a/.github/workflows/cdci.yml b/.github/workflows/cdci.yml
--- a/.github/workflows/cdci.yml
+++ b/.github/workflows/cdci.yml
@@ -118,6 +118,14 @@ jobs:
             echo "Error: One or more protected files have been modified."
             exit 1
           fi
+      - name: check streamlit report files for chatbot API
+        run: |
+          vuegen -c docs/example_config_files/Chatbot_example_config.yaml -output_dir tests/report_examples/chat_bot
+          if git diff tests/report_examples | grep .; then
+            echo Failed for report: $format
+            echo "Error: One or more protected files have been modified."
+            exit 1
+          fi
       - name: check for changes in report files
         run: |
           # write streamlit report to test folder 
