:construction: start to explore adding subsections to homesection (#125)
* :construction: start to explore adding subsections to homesection

* :sparkles: revert to homepage layout as before, add new section

- use the homepage layout as it was before: title, descrpiton, logo and graphical abstract
- if there are components in the main folder, trigger to add section with main folder name if the configuration is built using the directory based method.
  - a new section with the components is added
  - if configs are created manually, the first section is treated as every other section

* :bug: fix syntax error (two closing parantheses)

* 🐛 Make excel df paths relative insetad of absolute

* 🚧 add current state of qmd notebooks

- move html report file to correct place: update rel. paths
- add others as of now

* :bug: ignore description.md and empty sections

- do not use description as component in main folder
- the description is added to the key description

* :bug: resolve file path first

* :bug: fix issue with non-directory generated config files, add test

- do not treat first section special
- add example of how to run this config - check in cdci workflow

* :bug: fix path to tests/report_examples

* :bug: add correct file ending..

* ✅ test all report types based on quarto (update static path setting)

* :bug: bash for loop needs to be close using done

* :bug: get rid of absolute path (missed in #136)

- update tests
- make altair plot path relative to qmd file

* :art: clean-up comments/prints and improve logic

* 📝 Update example config files for basic and EMP case studies and update execution section of README

* 💚 Correct paths relative to the docs folder to pass CI tests

* 📝 Update README with details about running vuegen using the cofig exmaple files

* :bug: commit change to test from svg to png logo

---------

Co-authored-by: sayalaruano <sebasar1245@gmail.com>

diff --git a/.github/workflows/cdci.yml b/.github/workflows/cdci.yml
--- a/.github/workflows/cdci.yml
+++ b/.github/workflows/cdci.yml
@@ -109,6 +109,15 @@ jobs:
           cd docs
           vuegen -dir example_data/Earth_microbiome_vuegen_demo_notebook -rt jupyter
           vuegen -c example_data/Earth_microbiome_vuegen_demo_notebook/Earth_microbiome_vuegen_demo_notebook_config.yaml -rt jupyter
+      - name: quarto html report based on predefined config file
+        run: |
+          cd docs
+          vuegen -c example_config_files/Basic_example_vuegen_demo_notebook_config.yaml -output_dir ../tests/report_examples/Basic_example_vuegen_demo_notebook_cfg/html -rt html
+          # Check for changes
+          if git diff ../tests/report_examples | grep .; then
+            echo "Error: One or more protected files have been modified."
+            exit 1
+          fi
       - name: check for changes in report files
         run: |
           # write streamlit report to test folder 
@@ -118,7 +127,18 @@ jobs:
             echo "Error: One or more protected files have been modified."
             exit 1
           fi
-
+      - name: check for changes in quarto report files 
+        run: |
+          # write quarto based report to test folder
+          for format in html pdf docx odt revealjs pptx jupyter; do
+            vuegen -dir docs/example_data/Basic_example_vuegen_demo_notebook -output_dir tests/report_examples/Basic_example_vuegen_demo_notebook/$format  -rt $format 
+            # Check for changes
+            if git diff tests/report_examples | grep .; then
+              echo Failed for report: $format
+              echo "Error: One or more protected files have been modified."
+              exit 1
+            fi
+          done
 
   publish:
     name: Publish package to PyPI
